options:
  auto-update: true
  
chance: 2
debug: false

world-blacklist:
- world_nether
- world_the_end

custom:
  ExampleSurprise1:
    enabled: false
    lucklevel: LUCKY
    items:
      '1':
        type: DIAMOND_SWORD
        amount: 1
        displayname: '&c&l範例劍'
        lore:
          - '&7這是一條敘述.'
        enchants:
          - DAMAGE_ALL:5
  ExampleSurprise2:
    enabled: false
    lucklevel: LUCKY
    items:
      '1':
        slimefun_item: 'BIRTHDAY_CAKE'
        amount: 1
  ExampleSurprise3:
    enabled: false
    lucklevel: UNLUCKY
    commands:
      - 'tell {player} 你現在是個死人了!'
      - 'execute as {player} run summon zombie {x} {y} {z}'
