name: SlimefunLuckyBlocks
version: ${project.version}
description: 黏液科技附加 黏液幸運方塊 繁體翻譯版.
author: TheBusyBiscuit
website: https://github.com/TheBusyBiscuit/luckyblocks-sf/

api-version: 1.14
main: io.github.thebusybiscuit.slimefunluckyblocks.SlimefunLuckyBlocks

depend:
- Slimefun